[project]
name = "jovi-2024-dibartolomeo-benchmark"
version = "0.1.0"
description = "GLaDOS: Graph Layout algorithm Datasets for Open Science"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.3.6",
    "pandas>=2.2.3",
    "quarto-cli>=1.6.42",
]
